Edição de telefone e verificação via sms
utfpr-gp/servicebook pull request #123
Opened 2023-06-24 03:29 UTC by Dudalara

2023-06-27 01:30 UTC, ronifabio requested changes
- Não funciona!
- A validação do celular está aceitando qualquer código que se digita.
- Faltou usar máscara para o input do telefone
- Estamos usando este plugin: https://igorescobar.github.io/jQuery-Mask-Plugin/

2023-06-27 01:30 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +    private UserWizardUtil userWizardUtil;
Não deve usar o WizardUtil

2023-06-27 01:30 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        if (!oUser.isPresent()) {
- Precisa verificar se o usuário existe no banco de dados. Então, a frase em caso de não existir é: Usuário não encontrado. Ou então, emitir um EntityNotFoundException

2023-06-27 01:30 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        if (!oUser.isPresent()) {
Também verificar se o usuário autenticado tem exatamente o id passado na URL. Ou seja, verificar se ele tem permissão para alterar o dado do usuário. Não pode apresentar um formulário com dados para edição que não são do usuário. Em suma, se o usuário logado tem id 5 e for passado o id 3 na URL, não deve aceitar.

2023-06-27 01:30 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        if(!oUser.isPresent()) {
Note que authentication.getEmail retorna o usuário autenticado. Ele só executa o método se estiver autenticado por conta da anotação RolesAllowed.
Então, você tem que verificar se o usuário autenticado tem o mesmo id passado como parâmetro na rota. Ou seja, se tem permissão para alterar este dado.

2023-06-27 01:30 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        PhoneNumberVerificationService phoneNumberVerificationService = new PhoneNumberVerificationService(twilioAccountSid, twilioAuthToken, twilioVerifyServiceSid, phoneNumber);
Ok. Está solicitando para enviar o SMS com o código de verificação para o celular novo

2023-06-27 01:30 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        String phoneNumber = request.getParameter("phoneNumber");
Não usar request.getParamenter. Usar DTO para o formulário enviar os dados para o controller.

2023-06-27 01:30 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        Optional<Individual> oProfessional = this.individualService.findById(id);
Tem que verificar se o usuário logado tem o mesmo id do passado por parâmetro

2023-06-27 01:30 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        Optional<Individual> oProfessional = this.individualService.findById(id);
User UserService e não apenas IndividualService. Deve funcionar tanto para empresa quanto para indivíduo.

2023-06-27 01:30 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        PhoneNumberVerificationService phoneNumberVerificationService = new PhoneNumberVerificationService(twilioAccountSid, twilioAuthToken, twilioVerifyServiceSid, phoneNumber);
Não é para enviar o SMS aqui, já foi enviado no momento em que ele salvou o novo número.

2023-06-27 01:30 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        professional.setPhoneVerified(true);
Mesmo que caia no exception, vai executar esta linha. Então, sempre vai aparecer como verificado.

2023-06-27 01:30 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        Individual professional = oProfessional.get();
Usar User ao invés de Individual, também deve funcionar para empresa.

2023-06-27 01:30 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +            user.setPhoneVerified(false);
Não entendi pq mudou a verificação para falso novamente.

2023-06-29 02:47 UTC, Dudalara commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        PhoneNumberVerificationService phoneNumberVerificationService = new PhoneNumberVerificationService(twilioAccountSid, twilioAuthToken, twilioVerifyServiceSid, phoneNumber);
aqui ele só instanciou a classe de service para usar o verify

2023-07-01 11:46 UTC, ronifabio approved these changes

2023-07-01 11:46 UTC, closed without merging