Função para editar a senha implementada.
utfpr-gp/servicebook pull request #124
Opened 2023-06-27 00:02 UTC by tankesho

2023-06-27 01:49 UTC, ronifabio requested changes

2023-06-27 01:49 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +
Faltou verificar se o id passado como parâmetro refere-se ao usuário logado. Por exemplo, se o usuário logado tem id 5 e é passado o id 4 na URL, não pode haver a edição.

2023-06-27 01:49 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        if (!oUser.isPresent()) {
- Esta frase de erro não tem muito sentido. O que você fez foi buscar se existe um usuário com este id. A frase deveria ser de usuário não encontrado. A exception seria EntityNotFound

2023-06-27 01:49 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        mv.addObject("professional", userDTO);
Não há necessidade de passar este DTO se não for apresentar nada no formulário.

2023-06-27 01:49 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        Optional<User> oUser = this.userService.findByEmail(authentication.getEmail());
Está buscando o usuário autenticado

2023-06-27 01:49 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +            throw new EntityNotFoundException("Profissional não encontrado pelas informações fornecidas.");
Não faz muito sentido, aqui o erro seria de autenticação mesmo ao invés de EntityNotFound. Note que ele está autenticado e autorizado por conta da anotação RolesAllowed

2023-06-27 01:49 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        if(!oUser.isPresent()) {
Verificar também se o usuário logado tem o mesmo id passado na URL

2023-06-27 01:49 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        String newPassword = request.getParameter("new-password");
Não usar getParameter. Usar DTO para o pegar os dados do formulário. Tem vídeo explicando.

2023-06-28 01:53 UTC, tankesho commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        if (!oUser.isPresent()) {
resolvido

2023-06-28 01:53 UTC, tankesho commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +            throw new EntityNotFoundException("Profissional não encontrado pelas informações fornecidas.");
resolvido

2023-06-28 02:45 UTC, tankesho commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +
resolvido

2023-06-28 02:51 UTC, tankesho commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        mv.addObject("professional", userDTO);
resolvido

2023-06-28 02:57 UTC, tankesho commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
> +        if(!oUser.isPresent()) {
resolvido

2023-07-04 16:50 UTC, merged