Feature/edit profile pic
utfpr-gp/servicebook pull request #125
Opened 2023-06-27 20:15 UTC by cazueirobr

Adicionado a feature de edição de imagem ao clicar no texto "Editar perfil" abaixo da foto.

Ao clicar no texto é chamada uma função javascript que chama um formulário invisível e abre um input do tipo file para enviar a foto.

Se for utilizada uma chave da Inferdo (Filtro de imagens NSFW) será verificada se a imagem que está sendo enviada contém conteúdo impróprio. Caso exista um conteúdo impróprio será notificado que o perfil envie outra foto, caso não, haverá uma mensagem em verde indicando que a alteração ocorreu com sucesso.

2023-06-27 21:50 UTC, ronifabio requested changes

2023-06-27 21:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
>              Optional<User> oUser = userService.findByEmail(authentication.getEmail());
Fazer a verificação de usuário estar logado antes de mudar a foto. Mesmo que seja redundante esta verificação, é bom colocar. Certamente, só vai entrar no método se satisfazer o @RolesAllowed({RoleType.USER, RoleType.COMPANY})

2023-06-28 01:22 UTC, cazueirobr commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountController.java
>              Optional<User> oUser = userService.findByEmail(authentication.getEmail());
No ultimo refactor, acabei de fazer a mudança solicitada. Sendo assim está sendo verificado se o usuário está logado primariamente antes de qualquer coisa no método.

2023-07-04 02:20 UTC, ronifabio requested changes
- Não deixar ele subir qualquer tipo de arquivo, apenas deve aceitar PNG, JPG e SVG
- 
![image](https://github.com/utfpr-gp/servicebook/assets/3456733/f1773cbc-a342-4aa7-8813-5dec08ae25aa)

2023-07-05 18:54 UTC, cazueirobr commented
Atribuído o "accept" no input file do HTML para ficar sugestivo aos usuários selecionarem imagens em jpeg, jpg e png.
Também coloquei no controlador MyAccountController um método isValidateImage responsável por verificar se a imagem enviada foi de fato uma imagem. A partir disso ele ira verificar se poderá enviar a imagem para o cloudinary.

2023-07-05 18:59 UTC, cazueirobr commented
Atribuído o "accept" no input file do HTML para ficar sugestivo aos usuários selecionarem imagens em svg, jpg e png.
Também coloquei no controlador MyAccountController um método isValidateImage responsável por verificar se a imagem enviada foi de fato uma imagem. A partir disso ele ira verificar se poderá enviar a imagem para o cloudinary.

2023-07-06 01:22 UTC, merged