Feature/create entities
utfpr-gp/servicebook pull request #15
Opened 2021-05-06 13:22 UTC by CristhianAlbary

Criando entidades de acordo com o modelo de dados

2021-05-07 18:00 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Client.java
> +	private Long id;
Remover os ids das subclasses. O id da superclasse será usado.

2021-05-07 18:00 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Client.java
> +@PrimaryKeyJoinColumn(name="usuario_id")
Ao remover os ids das subclasses, esta anotação se torna desnecessária

2021-05-07 18:48 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Client.java
> +	@JsonIgnore
Remover @JsonIgnore, só é usado em apps REST para transformar para JSON. Mesmo assim, quem deve ser transformado para JSON são os DTOs e não as entidades.

2021-05-07 18:48 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Avaliation.java
> +	@JsonIgnore
Remover @JsonIgnore, só é usado em apps REST para transformar para JSON. Mesmo assim, quem deve ser transformado para JSON são os DTOs e não as entidades.

2021-05-07 18:49 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Category.java
> +	@JsonIgnore
Remover @JsonIgnore

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Avaliation.java
> +public class Avaliation {
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Avaliation.java
> +	@JsonIgnore
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Avaliation.java
> +	private BigDecimal rating;
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Avaliation.java
> +	private String comments;
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Category.java
> +public class Category {
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Category.java
> +	@JsonIgnore
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Client.java
> +@PrimaryKeyJoinColumn(name="usuario_id")
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Client.java
> +	private Long id;
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Client.java
> +	@JsonIgnore
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/JobCandidate.java
> +	private boolean chosen;
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/JobCandidate.java
> +	private boolean chosen_by_budget;
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/Professional.java
> +	private Long id;
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/User.java
> +	@Column(unique = true)
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/User.java
> +	private String profile_picture;
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/User.java
> +	private Date birth_date;
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/User.java
> +	private String phone_number;
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/User.java
> +	private boolean phone_verified;
Ajustado

2021-05-08 02:05 UTC, CristhianAlbary commented on src/main/java/br/edu/utfpr/servicebook/model/entity/User.java
> +	private boolean email_verified;
Ajustado

2021-05-08 13:56 UTC, ronifabio requested changes
- Remover a entidade Avaliation, colocar o rating global dentro da entidade Professional. Este será o rating calculado pela média de todas as especialidades que ele exerce.
- No relacionamento NxN entre Professional e Expertise, inserir um atributo rating. Este servirá para ter a nota do profissional para cada especialidade que exerce.
- Também haverá o rating do serviço, este ficar no JobContracted.
- Enfim, serão 3 ratings, uma para serviço, outro para expertise e outro para o profissional
- Mudar a cardinalidade dos relacionamentos que envolvem o JobContracted. O relacionamento entre JobContracted e Professional é 1xN, ou seja, um Profissional pode ser contratado para vários serviços e um serviço é realizado apenas por um profissional.
- Já o relacionamento entre JobRequest e JobContracted é realmente 1x1 mesmo.
- Estava pensando melhor, como é o profissional que precisa de avaliações para conseguir mais serviços e é este que é mais ativo no app, sendo que um cliente geralmente entrará de vez em quando, acho melhor o profissional finalizar um JobRequet, informar que o serviço foi realizado. Inclusive poderia postar foto do serviço realizado para servir de portfólio. Então, bastaria o profissional informar que o JobRequest foi finalizado e com isso, o cliente já poderá comentar e avaliar.
- Quando o profissional não libera para o cliente comentar via fechamento do JobRequest, pode ter ocorrido do serviço ter sido mau feito. Neste caso, o cliente pode denunciar o profissional e enviar um email para o adm contando o caso e com fotos comprovando que foi o profissional que realizou, inclusive com prints de conversas no whatsapp. Se houver 3 denúncias, o adm poderá intervir.
- Portanto, criar um atributo denounceAmount no Professional do tipo int.

2021-05-18 00:11 UTC, merged