Criado recurso CRUD cidades. Modificado  data.sql
utfpr-gp/servicebook pull request #16
Opened 2021-05-10 15:53 UTC by bruw

CRUD de cidades funcionando.

data.sql foi modificado porque estavam sendo feitas muitas  requisições desnecessárias .

2021-05-10 15:55 UTC, bruw commented
Falta a paginação de listas de cidades. Estou trabalhando neste recurso.

2021-05-10 16:35 UTC, Guilhn approved these changes

2021-05-11 15:01 UTC, ronifabio requested changes

2021-05-12 11:58 UTC, ronifabio approved these changes
Ótimo!

2021-05-12 11:58 UTC, merged