Criado o recurso de cadastrar cidades. Estr. do projeto semi-modelado.
utfpr-gp/servicebook pull request #2
Opened 2021-04-21 19:57 UTC by bruw

2021-04-21 20:01 UTC, Guilhn approved these changes

2021-04-21 23:14 UTC, ronifabio requested changes

2021-04-21 23:14 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/CityRegisterController.java
> +    public ModelAndView save(@RequestParam("name_city") String name_city, @RequestParam("id_state") String id_state){
Fazer o cadastro baseando-se no POST do projeto de exemplo crud-mvc. Receber um DTO como parâmetro, ao invés de usar RequestParam.
Ver vídeo: 02.15 - Funcionalidades de inserção e listagem de entidades - 8 min - https://www.loom.com/share/a484c2d5e0de45a8907146e60d349946

2021-04-22 01:04 UTC, Lamezon approved these changes

2021-04-23 12:26 UTC, ronifabio requested changes

2021-04-23 12:26 UTC, ronifabio commented on pom.xml
> +        <dependency>
Remover a dependência do validation-api, pois já tem o starter-validation que já inclui tal dependência

2021-04-23 12:26 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/entity/City.java
> +import com.sun.istack.NotNull;
Estranho este NotNull deste pacote com.sun. Favor verificar.

2021-04-23 12:26 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/entity/City.java
> +    @NotNull
Não usar tais validadores na entidade, mas apenas no DTO. Uma entidade deve ter apenas anotações de JPA e Lombok. Se quiser definir que a coluna do banco de dados não deve ser nula, aí deve usar @Column(nullable = false). O @NotNull que vc está querendo usar, deve ser do pacote de validação, mas as validações via Java devem ocorrer no DTO.

2021-04-23 12:26 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/entity/State.java
> +import com.sun.istack.NotNull;
Rever tal importação

2021-04-23 12:26 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/entity/State.java
> +    @NotNull
Não usar validação da api validation em entidade

2021-04-23 12:26 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/entity/State.java
>      @Column
Desnecessário apenas @Columns, sem nenhum atributo. É redundante. Qualquer atributo de uma entidade se tornará uma coluna na tabela.

2021-04-27 12:23 UTC, ronifabio requested changes

2021-04-28 18:13 UTC, ronifabio commented
Ok!

2021-04-28 18:14 UTC, ronifabio approved these changes

2021-04-28 18:15 UTC, merged