Validação dos campos no cadastro de uma requisição de serviço
utfpr-gp/servicebook pull request #25
Opened 2021-08-02 01:44 UTC by amand4

Adicionado validação nos campos de e-mail, nome e cep. Realizado a melhoria nas mensagens de erros e por fim, adicionado uma mascara no campo do nome no front.

2021-08-05 01:26 UTC, ronifabio requested changes
Precisa resolver as solicitações comentadas no código para a PR ser aprovada!

2021-08-05 01:26 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/dto/JobRequestDTO.java
> +    @Pattern(regexp="\\(\\d{2}\\)\\s\\d{4,6}-\\d{3,4}$",message="*Por favor, preencha um celular válido", groups = RequestClientInfoGroupValidation.class)
Deveria ter usado o seguinte `"^\\(?\\d{2}\\)?\\s?(\\d{4,5})-?(\\d{4})"`
Aceitar 4 ou 5 dígitos antes do hífen e depois apenas 4.

2021-08-05 01:26 UTC, ronifabio commented on src/main/webapp/assets/resources/scripts/name.js
> +    let regex = /(?:^|\s)(?!e|da|di|do|das|dos|de)\S/g
Não vi a necessidade deste código JS. Para um nome João de Sá, o 'de' precisa continuar minúsculo. Existem nomes assim. O REGEX que te passei contempla este caso.

2021-08-05 01:26 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/dto/JobRequestDTO.java
> +    @Pattern(regexp="\\(\\d{2}\\)\\s\\d{4,6}-\\d{3,4}$",message="*Por favor, preencha um celular válido", groups = RequestClientInfoGroupValidation.class)
Remover este * (asterisco) antes de Por favor, ....

2021-08-05 19:23 UTC, andredesouzaaranda requested changes
Necessário correções no REGEX.

2021-08-05 19:23 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/model/dto/JobRequestDTO.java
> +    @Pattern(regexp="\\(\\d{2}\\)\\s\\d{4,6}-\\d{3,4}$",message="*Por favor, preencha um celular válido", groups = RequestClientInfoGroupValidation.class)
Concordo.

2021-08-05 19:23 UTC, andredesouzaaranda commented on src/main/webapp/assets/resources/scripts/name.js
> +    let regex = /(?:^|\s)(?!e|da|di|do|das|dos|de)\S/g
Isso, imaginei o mesmo, meu nome contem "de", e ficaria "De".

2021-08-06 01:34 UTC, amand4 commented on src/main/webapp/assets/resources/scripts/name.js
> +    let regex = /(?:^|\s)(?!e|da|di|do|das|dos|de)\S/g
Ok, vou remover pessoal. Objetivo era tratar caso o usuário digitar o 'd' Maiúsculo ou esquecer de iniciar o nome com a letra Maiúscula.

2021-08-06 01:35 UTC, amand4 commented on src/main/java/br/edu/utfpr/servicebook/model/dto/JobRequestDTO.java
> +    @Pattern(regexp="\\(\\d{2}\\)\\s\\d{4,6}-\\d{3,4}$",message="*Por favor, preencha um celular válido", groups = RequestClientInfoGroupValidation.class)
Ok.

2021-08-06 15:50 UTC, andredesouzaaranda approved these changes
Ok!

2021-08-06 15:54 UTC, andredesouzaaranda approved these changes
Ok!

2021-08-06 17:32 UTC, ronifabio approved these changes

2021-08-06 17:33 UTC, merged