Adicionado conta do profissional
utfpr-gp/servicebook pull request #33
Opened 2021-08-13 19:54 UTC by andredesouzaaranda

2021-08-16 20:12 UTC, ronifabio requested changes
O código está ok em relação às boas práticas, apenas falta fazer algumas validações em relação ao profissional e suas especialidades.

2021-08-16 20:12 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +                throw new InvalidParamsException("O id informado não pode ser negativo.");
Alterar para "O identificador da especialidade não pode ser negativo. Por favor, tente novamente."

2021-08-16 20:12 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +            if (!expertise.isPresent()) {
Faltou verificar se o id da especialidade passado como parâmetro é realmente de uma especialidade do profissional logado. Quando vc busca por findId(), está buscando globalmente, mas não só nas especialidades do profissional.

2021-08-17 00:45 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +        Optional<Professional> oProfessional = Optional.ofNullable(professionalService.findByEmailAddress(CurrentUserUtil.getCurrentUserEmail()));
Corrigido.

2021-08-17 00:45 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +                throw new InvalidParamsException("O id informado não pode ser negativo.");
Corrigido.

2021-08-17 00:45 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +            if (!expertise.isPresent()) {
Corrigido.

2021-08-17 20:19 UTC, ronifabio approved these changes
Ok!

2021-08-17 20:19 UTC, merged