Cadastro de usuário
utfpr-gp/servicebook pull request #39
Opened 2021-08-30 19:30 UTC by andredesouzaaranda

2021-08-30 20:17 UTC, ronifabio requested changes
- O código de autenticação precisaria ser de 6 dígitos, para o usuário ler, memorizar e digitar. Não um código assim: 73f28c2c-e53d-4a8d-8fe7-541b0c17b371
- Faltou máscara no campo de telefone
- Faltou máscara no CPF, suportar apenas números também
- Faltou a tela de senha e confirmação de senha

2021-08-30 20:17 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +        if (dto.getCode() != null) {
Esta verificação está errada. Usa @NotBlank no atributo código no DTO.

2021-08-30 20:17 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +            if (oUserCode.isPresent()) {
Poderia fazer a refatoração para evitar estes elses. Primeiramente, verificar se o oUserCode está presenta no BD. Depois, caso passe por este if, verifica se o código é igual o persistido. Aquele trecho `if (errors.hasErrors()) {
            model.addAttribute("dto", dto);
            model.addAttribute("errors", errors.getAllErrors());

            return "visitor/user-registration/wizard-step-02";
        }` poderia colocar num método e chamar a cada if com para realizar o return

2021-08-30 20:17 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/dto/UserDTO.java
> +public class UserDTO implements Serializable {
Usar `@NotBlank` nos campos obrigatórios

2021-08-30 20:17 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/dto/UserDTO.java
> +    private AddressDTO address;
Se o AddressDTO precisa ser validado junto, incluir `@Validated` nesta linha também. Caso contrário, será ignorado.

2021-08-30 20:17 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +        if (dto.getCode() != null) {
- Desnecessário, usar `NotBlank` no DTO

2021-08-30 20:17 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +                if (dto.getCode().equals(oUserCode.get().getCode())) {
Refatorar para evitar tantos aninhamentos, incluir o trecho que retorna o erro ao cliente em um método. Tentar usar ifs sem else.

2021-08-30 20:17 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +            oUser = userService.findByName(dto.getName());
Mas o nome não é único, pode existir mais de uma pessoa no mundo com o mesmo nome.

2021-08-30 21:05 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/model/dto/UserCodeDTO.java
> +    private String email;
Atributo necessário para vincular um código a um email.

2021-08-30 21:07 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +        if (dto.getCode() != null) {
Esta verificação é do código submetido pelo usuário.

2021-08-30 21:13 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/model/dto/UserDTO.java
> +public class UserDTO implements Serializable {
Se usar, irá retornar mais de uma mensagem de erro!

2021-08-30 21:19 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +        if (dto.getCode() != null) {
Sim, mas a sugestão é usar a anotação `@NotBlank` no DTO. Assim, já na chamada do método POST, o DTO é validado pelo @Validated e verifica que o código está vazio e o erro é preenchido automaticamente no BindingResult.

2021-08-30 21:20 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/model/dto/UserDTO.java
> +    private AddressDTO address;
Usado somente para transferência de dados. O responsável pela validação é o AddressDTO e não o UserDTO.

2021-08-30 21:21 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/dto/UserCodeDTO.java
> +    private String email;
Mas verifique se está usando este atributo. No código, parece que vc está usando do sessionDTO. Este atributo é importante, por isso deveria ter a anotação @NotNull ou @NotBlank. Ele seria bastante útil quando o código fosse para o email como um link também.

2021-08-30 21:23 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/dto/UserDTO.java
> +public class UserDTO implements Serializable {
Se você está com medo que retorno muitos erros por conta de ser formulário wizard, aquela prática de usar os grupos de validação é exatamente para evitar isso. No método POST vc especifica qual grupo será avaliado, não todo o DTO que é avaliado a cada POST, apenas aqueles atributos que estão no grupo informado.

2021-08-30 21:24 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +        if (dto.getCode() != null) {
Ahh tá entendi, valeu prof!

2021-08-30 21:26 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +        if (dto.getCode() != null) {
Não entendi.

2021-08-30 21:28 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +            oUser = userService.findByName(dto.getName());
Vdd, rsrsr! Na pressa passou batido! Ok vou verificar!

2021-08-30 22:18 UTC, andredesouzaaranda commented on pom.xml
> +            <version>2.5.4</version>
Corrigido!

2021-08-30 22:19 UTC, andredesouzaaranda commented on pom.xml
> +            <artifactId>spring-context-support</artifactId>
Removido e corrigido!

2021-08-30 22:19 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +            errors.rejectValue("email", "error.dto", "Email já cadastrado! Por favor, insira o email.");
Corrigido!

2021-08-30 22:27 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/model/dto/UserCodeDTO.java
> +    private String email;
Está sendo usado para persistir o userCode(email, code). O email é validado no userDTO. 

```
           String code = authenticationCodeGeneratorService.generateAuthenticationCode();

            UserCodeDTO userCodeDTO = new UserCodeDTO(dto.getEmail(), code);
            UserCode userCode = userCodeMapper.toEntity(userCodeDTO);

            userCodeService.save(userCode);
            emailSenderService.sendEmailToServer(dto.getEmail(), "Servicebook: Código de autenticação.", "Código de autenticação:"
```

2021-08-30 22:28 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +        if (dto.getCode() != null) {
Corrigido!

2021-08-30 22:39 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +            if (oUserCode.isPresent()) {
A ideia original era esta, porém, depois de analisar vi que para min a legibilidade ficaria comprometida, principalmente por estar extraindo a estrutura de decisão para "mais uma estrutura de decisão". Pensei em fazer isto, porém estaria criando dois if's para o mesmo contexto de problema, ou seja a mesma verificação!

Corrigido!

2021-08-30 22:48 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/model/dto/UserDTO.java
> +public class UserDTO implements Serializable {
Sim, todos os grupos são especificados separadamente!

Corrigido!

2021-08-30 22:50 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/model/dto/UserDTO.java
> +    private AddressDTO address;
O AddressDTO é validado separadamente!

Ok!

2021-08-30 22:51 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +        if (dto.getCode() != null) {
Na solicitação acima foi pedido para incluir o @NotBlank!

Corrigido!

2021-08-30 22:53 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +                if (dto.getCode().equals(oUserCode.get().getCode())) {
Corrigido!

2021-08-30 22:54 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +            oUser = userService.findByName(dto.getName());
Corrigido!

2021-09-01 00:35 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/controller/UserRegistrationController.java
> +        if (dto.getCode() != null) {
Atualizado para usar REGEX.

2021-09-01 00:39 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/model/dto/UserDTO.java
> +public class UserDTO implements Serializable {
Atualizado para usar REGEX e anotações próprias do Spring como @CPF, @Email.

2021-09-01 00:39 UTC, andredesouzaaranda commented on src/main/java/br/edu/utfpr/servicebook/model/dto/UserDTO.java
> +    private AddressDTO address;
Atualizado para AddressFullDTO e adicionado anotação @Valid.

2021-09-02 18:25 UTC, ronifabio approved these changes
Aprovado!

2021-09-02 18:26 UTC, merged