Adicionado botões para o usuários alternar de modo cliente para modo profissional nas visões my-requests e my-account.
utfpr-gp/servicebook pull request #41
Opened 2021-11-22 23:44 UTC by Roliveira96

Adicionado botões para o usuários alternar de modo cliente para modo profissional nas visões my-requests e my-account.

2021-11-22 23:55 UTC, ronifabio requested changes

2021-11-22 23:55 UTC, ronifabio commented on src/main/webapp/WEB-INF/view/professional/my-account.jsp
> +                                ESPECIALIDADES
Duplicação do trecho de especialidades

2021-11-22 23:56 UTC, pedrosezar approved these changes

2021-11-22 23:58 UTC, BeaFernandes approved these changes

2021-11-23 00:02 UTC, ronifabio approved these changes
Aprovado!

2021-11-23 00:03 UTC, merged