Adicionada opção para pesquisar profissional pelo nome
utfpr-gp/servicebook pull request #46
Opened 2021-12-07 22:53 UTC by BeaFernandes

2021-12-08 22:00 UTC, pedrosezar approved these changes

2021-12-08 22:48 UTC, ronifabio requested changes

2021-12-08 22:48 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/SearchController.java
> +        List<City> cities = cityService.findAll();
- Esta lista de cidades não está aparecendo na página.

2021-12-08 22:48 UTC, ronifabio commented on src/main/webapp/WEB-INF/view/visitor/search-results.jsp
> +        <div id="index-banner" class="parallax-container">
- As cidades não estão aparecendo
- Ademais, código duplicado com index.jsp, usar o comando include ou criar uma tag para não haver duplicidade desta seção inicial do JSP

2021-12-08 22:48 UTC, ronifabio commented on src/main/webapp/WEB-INF/view/visitor/search-results.jsp
> +                            <c:forEach var="professional" items="${professionals}">
- Mostrar uma emoji de triste e a frase que não foram encontrados profissionais.
- Segue um exemplo:
```
<c:if test="${empty jobs}">
    <div class="container">
        <div class="row">
            <div class="col s12 spacing-buttons">
                <div class="none-profission center">
                    <i class="material-icons large"> sentiment_dissatisfied </i>
                    <p class="center text-form-dados">
                        Nenhuma solicitação para fazer encontrada!
                    </p>
                </div>
            </div>
        </div>
    </div>
</c:if>
```

2021-12-08 22:48 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/SearchController.java
> +@RequestMapping("/buscar")
- Seguindo as diretivas REST, um nome de rota não pode ser um verbo. Verbos são os próprios GET, POST, PUT...
- As rotas devem ser substantivos e no preferencialmente no plural. Deste modelo, num ProfessionalController, a rota seria /profissionais. O GET padrão chamaria o findAll, ou seja, retornaria a lista de clientes.
- No seu caso, você criou um novo controller, o SearchController, mas poderia ter usado o ProfessionalController, mais apropriado para a siatuação.
- Então, ou muda este seu método para o ProfessionalController ou renomeie a rota raíz de /buscar para /profissionais/busca
-

2021-12-08 22:48 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/dto/ProfessionalDTO.java
> +    public String getOnlyNumbersFromPhone() {
Parece que não está sendo usado, remover!

2021-12-12 15:36 UTC, BeaFernandes commented on src/main/java/br/edu/utfpr/servicebook/model/dto/ProfessionalDTO.java
> +    public String getOnlyNumbersFromPhone() {
Estou utilizando no arquivo src/main/webapp/WEB-INF/view/visitor/professional-details.jsp, para poder gerar o link de redirecionamento para o chat no WhatsApp:
`<div class="row center-align">
                    <a href="https://web.whatsapp.com/send?phone=55${professional.getOnlyNumbersFromPhone()}" target="_blank">`

2021-12-12 16:01 UTC, BeaFernandes commented on src/main/java/br/edu/utfpr/servicebook/controller/SearchController.java
> +        List<City> cities = cityService.findAll();
Professor, aqui pra mim, essa lista nunca apareceu nem no index. Como fica aí pra você?

2021-12-13 22:54 UTC, ronifabio approved these changes

2021-12-13 22:54 UTC, merged