Criado o cadastro de profissões
utfpr-gp/servicebook pull request #5
Opened 2021-04-24 02:03 UTC by rgoudinho

2021-04-24 19:03 UTC, Lamezon approved these changes

2021-04-24 20:53 UTC, bruw commented on src/main/java/br/edu/utfpr/servicebook/controller/ProfessionController.java
> +        return "redirect:/profissao";
Acho que seria interessante você validar se a profissão já existe na base de dados, para não haver redundância gravando ela mais de uma vez. Não sei se é a melhor implementação, mais você pode usar a validação que eu criei para cidade e adaptar para o cadastro de profissão. 

Verifique este meu commit: 
https://github.com/utfpr-gp/servicebook/pull/2/commits/e6abe77e2529fda507282611b53c9505b62ce209

nele está o código necessário para realizar a validação. Caso necessite de ajuda é só chamar!

2021-04-26 02:24 UTC, rgoudinho commented on src/main/java/br/edu/utfpr/servicebook/controller/ProfessionController.java
> +        return "redirect:/profissao";
Aaa sim, obrigado pelo comentário, vou dar uma olhada no seu código, caso eu precise, peço ajuda sim...

2021-04-27 12:22 UTC, ronifabio requested changes

2021-04-28 19:49 UTC, ronifabio commented
Ronaldo, o seu branch está em conflito com o develop. O develop já recebeu algumas alterações depois que você criou o seu branch profession-registration. Então, para este Pull Request (PR) ser aceito, resolva os conflitos(manualmente) e então faça o push novamente!

2021-04-29 20:17 UTC, Guilhn approved these changes

2021-04-29 21:54 UTC, ronifabio commented
Ronaldo, você conseguiu executar o cadastro após a modificação da rota para /profissoes? 
Neste seu branch, o action está assim `<form action="profissao" method="post">`
`/profissao` no singular

2021-04-29 21:55 UTC, ronifabio commented
Ao cadastrar, está faltando apresentar a mensagem de cadastrado com sucesso.

2021-04-29 21:58 UTC, ronifabio commented
Também está faltando apresentar as mensagens de problema de validação. Ao cadastrar um campo vazio, nada aparece. Sendo que o nome no DTO está como notEmpty

2021-04-29 21:59 UTC, ronifabio commented
Se cadastrar a mesma profissão duas vezes, deve aparecer a mensagem de que a profissão já está cadastrada. Não aparece!

2021-05-04 00:55 UTC, ronifabio requested changes
Realizar as mudanças solicitadas.

2021-05-04 00:55 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/dto/ProfessionDTO.java
> +    private long id;
O id precisa ser classe Long. Aí se não estiver setado, será nulo. Quando é long primitivo, o default é zero. Não é a mesma coisa que null, não se tem certeza se o atributo não foi setado ou foi setado com zero.

2021-05-04 00:55 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/dto/ProfessionDTO.java
>      private String name;
Quando é String, usar @NotBlank. @NotEmpty suporta strings " " vazias com espaços.

2021-05-04 14:07 UTC, ronifabio requested changes
Ok. Apenas resolva os conflitos com a versão atual do `develop` para realizar o merge.

2021-05-04 20:56 UTC, ronifabio approved these changes
Ok. Mas trabalhar em uma nova branch para criar um CRUD completo para profissões.

2021-05-04 20:57 UTC, merged