Melhorias no Wizard de criação de Job
utfpr-gp/servicebook pull request #54
Opened 2021-12-17 11:32 UTC by Roliveira96

Agora existe uma tela, no qual é digitado o e-mail e o mesmo confere se o usuário existe no sistema, caso sim ele é redirecionado para a tela de login, caso contrário ele é redirecionado para a tela de cadastro.

2021-12-17 12:12 UTC, ronifabio requested changes
- Ao clicar no botão, ACOMPANHE SUA SOLICITAÇÃO, isso no último passo do WIZARD, enviar para a tela de login.
- Quando o email já está cadastrado, apresentar a tela de login com senha. 
- 
![image](https://user-images.githubusercontent.com/3456733/146541408-289b983c-723f-4300-bc61-07522e38911b.png)
- Como o login não está implementado. Simule usando o usuário que está na classe util CurrentUserUtil. Assim, ao clicar no botão de entrar, os dados são pegos daquele usuário. E então, é apresentada a tela final, dizendo que o pedido foi enviado com sucesso.
- O botão VOLTAR do último passo está voltando para a tela de carregar foto ao invés de voltar para a tela de colocar email.

2021-12-17 12:12 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/JobRequestController.java
> +        if (dto.getExpertiseId() != null) {
- Tente sempre fazer uma lógica que verifique os erros antes ao invés de verificar se está ok.
- No caso, verifique se dto.getExpertiseId() == null igual a nulo e não se é diferente de nulo.
- Se for nulo, já emita um exception
- Esta prática evita os ifs aninhados. O código fica mais limpo.
- Vai validando e emitindo exception ou colocando no rejectValue
- No caso do expertiseID, por estar no DTO, lá já é verificado com a anotação @NotNull, verifique no JobRequestDTO
- Assim, este if de verificação de nulo é desnecessário, remover.

2021-12-17 12:12 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/JobRequestController.java
> +                errors.rejectValue("expertiseId", "error.dto", "Especialidade não encontrada! Por favor, selecione uma especialidade profissional.");
- Neste caso seria um exception e não um erro de validação.
- O id é um campo válido em termos de formatação, mas não foi encontrado.
- Emitir a exception: EntityNotFoundException

2021-12-17 12:12 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/JobRequestController.java
> +        if (oExpertise.isPresent()) {
- Verificar se é nulo e então emitir um exception
- Não pode cadastrar um JOB sem Expertise

2021-12-18 21:08 UTC, Roliveira96 commented on src/main/webapp/WEB-INF/view/client/job-request/wizard-step-login-user.jsp
> +                                            <button class="waves-effect waves-light btn">Finalizar</button>
resolvido, ira ser enviada no próximo comiit

2021-12-21 22:49 UTC, Roliveira96 commented on src/main/webapp/WEB-INF/view/client/job-request/wizard-step-login-user.jsp
> +                        <h3 class="center grey-text"><strong>Último passo!</strong></h3>
Mudado, essa correção irá para o próximo commit

2021-12-21 22:51 UTC, Roliveira96 commented on src/main/java/br/edu/utfpr/servicebook/controller/JobRequestController.java
> +        if (dto.getExpertiseId() != null) {
Essa parte não fui eu que fiz, mas se quiser posso remover.

2022-05-24 18:53 UTC, closed without merging