Barra de Progresso Job
utfpr-gp/servicebook pull request #55
Opened 2021-12-18 20:18 UTC by Roliveira96

Foi adicionado uma barra de progresso para o candidato consiga saber quantas candidaturas aquele job já possui.

2021-12-18 20:42 UTC, ronifabio requested changes

2021-12-18 20:42 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +        mv.addObject("job", jobFull);
Redundante, está incluindo duas vezes

2021-12-18 20:42 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +        mv.addObject("job", jobFull);
Apagar mv.addObject("ricardo", "ricardo");

2021-12-18 20:42 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +            amountOfCandidates = jobFull.getAmountOfCandidates();
Renomear jobFull para jobRequestDetailsDTO

2021-12-18 20:42 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
>          mv.addObject("client", client);
Transformar Client em DTO para passar para a camada de view

2021-12-18 20:42 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +        quantityCanditatorMax = jobFull.getQuantityCandidatorsMax();
- Não usar o DTO jobFull para acessar um dado importante, use jb JobRequest.
- Isso pq se alguém mudar o Mapper, o DTO poderá vir sem este dado, mesmo que o dado exista no banco de dados

2021-12-18 20:42 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +        if (jobFull.getAmountOfCandidates() == null)
Usar jb ao invés de DTO para acessar o dado

2021-12-23 11:54 UTC, Roliveira96 commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +            amountOfCandidates = jobFull.getAmountOfCandidates();
Renomeado.

2021-12-23 12:26 UTC, Roliveira96 commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +        quantityCanditatorMax = jobFull.getQuantityCandidatorsMax();
Olá professor, tudo bem? 
Realmente é errado, porém eu consegui alguns métodos estão somente presente no JobRequestDTO e outro do JobRequest.

![image](https://user-images.githubusercontent.com/14916078/147240296-c4db49ba-3fad-46e0-886d-c786d7f1f3bd.png)

Realizei as alterações no Controller MyAccountProfessionalController, para a forma desejada.

2021-12-23 12:26 UTC, Roliveira96 commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +        quantityCanditatorMax = jobFull.getQuantityCandidatorsMax();
Olá professor, tudo bem? 
Realmente é errado, porém eu consegui alguns métodos estão somente presente no JobRequestDTO e outro do JobRequest.

![image](https://user-images.githubusercontent.com/14916078/147240296-c4db49ba-3fad-46e0-886d-c786d7f1f3bd.png)

Realizei as alterações no Controller MyAccountProfessionalController, para a forma desejada.

2021-12-23 12:35 UTC, Roliveira96 commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
>          mv.addObject("client", client);
Resolvido.

2021-12-23 12:36 UTC, Roliveira96 commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +        mv.addObject("job", jobFull);
Resolvido.

2021-12-23 12:37 UTC, Roliveira96 commented on src/main/java/br/edu/utfpr/servicebook/controller/MyAccountProfessionalController.java
> +        if (jobFull.getAmountOfCandidates() == null)
O metodo getAmountOfCandidates é somente do DTOS e não do modelo JobRequest.

2022-05-24 18:54 UTC, closed without merging