Adicionado validação de telefone
utfpr-gp/servicebook pull request #62
Opened 2022-05-16 21:37 UTC by alanmihcnk

Está enviando um código de 6 digitos para o número cadastrado no Twilio e validando caso o código esteja correto. Tem um erro ao inserir o código errado, mas já estava presente antes de adicionar a validação.

2022-05-17 01:12 UTC, ronifabio requested changes

2022-05-23 20:43 UTC, ronifabio requested changes

2022-05-23 20:43 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/util/NumberValidator.java
> +                VERIFY_SID, codeSms).setTo(this.number).create();
Caso o serviço esteja indisponível ou por outro motivo, ocorra um erro, evitar que a aplicação quebre. Trate a exceção gerada e informe que não foi possível enviar o SMS, que é para ele validar posteriormente.

2022-05-23 20:43 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/util/NumberValidator.java
> +                .create();
Está dando erro para enviar o SMS
com.twilio.exception.ApiException: Authenticate
	at com.twilio.rest.verify.v2.service.VerificationCreator.create(VerificationCreator.java:240) ~[twilio-8.29.1.jar:na]
	at com.twilio.rest.verify.v2.service.VerificationCreator.create(VerificationCreator.java:23) ~[twilio-8.29.1.jar:na]
	at com.twilio.base.Creator.create(Creator.java:40) ~[twilio-8.29.1.jar:na]
	at br.edu.utfpr.servicebook.util.NumberValidator.sendVerifySms(NumberValidator.java:50) ~[classes/:na]

2022-05-23 22:03 UTC, alanmihcnk commented on src/main/java/br/edu/utfpr/servicebook/util/NumberValidator.java
> +                .create();
Esse erro ocorre sempre que é executado em um máquina diferente. Não tem solução para automatizar, precisa entrar no Twilio e pegar o novo Auth Token.

2022-05-24 18:49 UTC, ronifabio commented
Resolver os conflitos e corrigir apontamentos realizados.
Colocar um <bloquote>na página de digitação do telefone no cadastro, informando ao desenvolvedor que ele precisa gerar uma chave particular de autenticação para o twillio enviar o SMS.
Na mensagem, informar o login, senha e link para gerar a nova chave.
Esta mensagem será útil para a turma corrente e principalmente para as demais.

2022-06-01 02:17 UTC, ronifabio approved these changes
Aprovado!

2022-06-01 02:17 UTC, merged