Adicionado função para remoção de codigos expirados
utfpr-gp/servicebook pull request #69
Opened 2022-06-04 21:06 UTC by luispaganini

Adicionado Job para remoção de codigos expirados no cadastro com email a cada 24 horas

2022-06-06 11:50 UTC, ronifabio requested changes

2022-06-06 11:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/IndividualRegisterController.java
> +        quartzService.verifyExpiredTokenEmailJob(actualCode);
- Este Job precisa ser executado todos os dias, intermitentemente.
- Cadastrar o job depois da inicialização da aplicação. No cartão do Trello tem um artigo com as formas de executar código após a inicialização da app.
- User o CommandLineRunner ou o @EventListener.

2022-06-06 11:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/jobs/VerifyExpiredTokenEmailJob.java
> +        String code = (String) jobDataMap.get("userCode");
- Nesta implementação, não será passado parâmetros para o Job.
- O Job precisa pegar os dados direto do BD.
- Então, ele vai executar uma vez por dia, no momento em que ele executar, ele tem que fazer uma busca no BD por tokens já expirados.
- Como a entidade já tem o atributo expiratedDate, basta você pegar a data corrente e fazer um select buscando tokens com expiratedDate menor do que a data atual.
- Estes já estão expirados.
- Estes serão retornados como  resultado de busca.
- Basta deletar todas estas entidades.

2022-06-06 11:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/jobs/VerifyExpiredTokenEmailJob.java
> +            Optional<UserCode> userCode = userCodeService.findByCode(code);
- Não vai buscar por id, vai buscar por códigos expirados no BD.

2022-06-06 11:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/service/QuartzService.java
> +            scheduler = factory.getScheduler();
- Este trecho redundante pode ir para o método init(), uma vez que teremos apenas um scheduler.
```
scheduler = factory.getScheduler();
scheduler.setJobFactory(jobFactoryCDI);
```

2022-06-06 11:50 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/service/QuartzService.java
> +    private Trigger getTriggerPerDay(String name, String group) {
- Usar a sintaxe de CRON para agendar o Job.
- Lembre que você vai agendar uma vez só, no início da app.
- Se a app foi inicializada e rodar por 10 anos, sem ser reinicializada, este Job precisaria ser disparado no início e executar constantemente a cada dia.
- Segue o tutorial com a sintaxe do CRON: http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html

2022-06-22 18:56 UTC, ronifabio requested changes

2022-06-22 18:56 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/IndividualRegisterController.java
> +        quartzService.verifyExpiredTokenEmailJob();
Remover esta chamada, uma vez que este cadastro de Job já foi feito no início da aplicação.

2022-06-22 18:56 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/jobs/VerifyExpiredTokenEmailJob.java
> +            List<UserCode> userCode = userCodeService.findAll();
A filtragem por códigos expirados devem ser feitos no banco de dados, não na aplicação. Buscas no BD apresenta maior performance do que fazer na aplicação. Ou seja, não use findAll. Crie um método no repository para retornar apenas as entidades expiradas, tal como foi apresentado na aula via Meet.

2022-06-22 19:01 UTC, luispaganini commented on src/main/java/br/edu/utfpr/servicebook/jobs/VerifyExpiredTokenEmailJob.java
> +            List<UserCode> userCode = userCodeService.findAll();
Seria necessário dar uma revisada no método apresentado na aula, pois aquele estava incorreto.

2022-06-25 23:30 UTC, ronifabio approved these changes

2022-06-25 23:30 UTC, merged