Adicionado cadastro de especialidade com upload de icone svg
utfpr-gp/servicebook pull request #74
Opened 2022-06-22 02:29 UTC by dviniciusbonin

2022-06-25 18:54 UTC, ronifabio requested changes
- Mesmo passando a imagem com formato errado, apresenta a mensagem de erro de que a profissão já foi cadastrada.
- Então, quando der erro de formato de imagem, mostrar a mensagem: Opsss! Formato de imagem não suportado. É aceito apenas o formato SVG. 
- Faltou apresentar o ícone cadastrado na listagem de especialidades logo abaixo do formulário.
- Ao editar, mostrar o endereço da imagem dentro do campo de upload
- Está havendo erro ao deletar uma especialidade.

2022-06-25 18:54 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/ExpertiseController.java
> +    @SneakyThrows
- Remover esta anotação

2022-06-25 18:54 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/ExpertiseController.java
> +        if (!optionalProfession.isPresent() && isValidateImage(dto.getIcon())) {
- Tratar o exception IOException com try-catch e então, apresentar a mensagem de formato errado de imagem no campo de erro (quadro vermelho) na mesma página do formulário.

2022-06-25 18:54 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/controller/ExpertiseController.java
>              List<Expertise> professions = expertiseService.findAll();
- Não percebi que esteja usando este professions e professionDTOs. Caso não esteja realmente usando, favor remover esta pesquisa.

2022-06-25 18:54 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/dto/ExpertiseDTO.java
> +    private MultipartFile icon;
Tornar obrigatório.

2022-06-25 18:54 UTC, ronifabio commented on src/main/java/br/edu/utfpr/servicebook/model/dto/ExpertiseDTO.java
> +    private String description;
Tornar obrigatório.

2022-06-29 03:53 UTC, dviniciusbonin commented on src/main/java/br/edu/utfpr/servicebook/model/dto/ExpertiseDTO.java
> +    private MultipartFile icon;
Deixei opcional para que não quebre o data.sql

2022-06-29 03:58 UTC, dviniciusbonin commented
Corrigi a listagem e o update da especialidade. Porém não consegui setar o caminho da imagem no input do tipo file na hora do update(Não sei se é possível), acho que para esse caso teria que ver outra estratégia.
Em relação ao erro do tipo do arquivo, não consegui visualizar pois ele não permite adicionar outro tipo de imagem que não seja svg.

2022-06-29 14:22 UTC, ronifabio requested changes
- Redimensionar o ícone na tabela para ser apresentado na linha.
![image](https://user-images.githubusercontent.com/3456733/176453759-c4bf9654-e9a4-4acb-8935-0877811ff4a0.png)
- Na remoção, quando a especialidade é usada como chave estrangeira em outras entidades, informar numa mensagem no mesmo formulário como a seguinte: A especialidade não pode ser removida, pois está atribuída a profissionais e ordens de serviço.
- Mudar o texto do botão de CHOOSE FILE para Adicionar ícone
- Na edição, para aparecer o nome do arquivo no input de upload, passe uma String no atributo value e não um MultipartFile. Pegue o exemplo do city-register.jsp.

2022-06-29 14:25 UTC, ronifabio commented
Atualize o seu branch com o commit que realizei: [Refatoração do cadastro de uma especialidade](https://github.com/utfpr-gp/servicebook/pull/74/commits/c599c95ff257eadfed891477c182941634fc7dd6)

2022-07-01 01:42 UTC, dviniciusbonin commented
Corrigido dimensões do icone
Adicionado tratamento de erro no delete
Propriedades adicionadas como obrigatório

Ainda com problema para implementar o update mantendo o mesmo ícone

2022-07-04 22:58 UTC, merged