Feature/send email again
utfpr-gp/servicebook pull request #86
Opened 2022-10-24 03:39 UTC by isabela-tvitek

2022-10-25 02:32 UTC, isabela-tvitek commented
Apontado branch para a develop

2022-10-25 21:26 UTC, ronifabio requested changes
É preciso fazer alguns ajustes na chamada Ajax para ser aprovado.

2022-10-25 21:26 UTC, ronifabio commented on src/main/webapp/WEB-INF/view/visitor/user-registration/wizard-step-02.jsp
> +            "url": "http://localhost:8080/servicebook/cadastrar-se/passo-1?email=${dto.email}",
Como é um método POST, não é uma boa prática passar o parâmetro via URL. É preciso passar no corpo da mensagem. Como está usando JQuery, veja o uso do $.post() [jQuery.post()](https://api.jquery.com/jquery.post/) e envie um json no segundo argumento da função, ou seja, parâmetro data.

2022-10-25 21:26 UTC, ronifabio commented on src/main/webapp/WEB-INF/view/visitor/user-registration/wizard-step-02.jsp
> +        var settings = {
Use let ao invés de var para declarar variáveis.

2022-11-01 15:09 UTC, ronifabio commented
Isabela, favor resolver os conflitos e enviar um novo push após a resolução dos conflitos.

2022-11-01 15:10 UTC, ronifabio requested changes
Isabela, favor resolver os conflitos e então, ressubmeter para merge.

2022-11-03 13:19 UTC, ronifabio approved these changes

2022-11-03 13:19 UTC, merged