Feature/refactor links
utfpr-gp/servicebook pull request #93
Opened 2022-11-08 02:04 UTC by isabela-tvitek

2022-11-21 21:50 UTC, AmandaCarolyneDeLima approved these changes

2022-11-22 17:36 UTC, ronifabio requested changes
- O botão anunciar que está no menu, não funciona. Redirecionar para a página inicial do formulário wizard para cadastro de uma solicitação de serviço.
- Mostrar o nome do usuário até x caracteres no segundo dropdown, depois coloca ... 
- Ao selecionar um perfil, tipo COMO PROFISSIONAL, manter este nome como texto do dropdown. Sempre está aparecendo o texto MINHA CONTA.
- Ver o problema do ícone que está aparecendo o texto em algumas situações.
- Quando ele clicar em Meu Perfil, redirecionar para http://localhost:8080/servicebook/minha-conta/perfil
- Os botões "Como Funciona?" e "Anunciar" estão pequenos e decentralizados. Veja o exemplo do OLX, botões alinhados.
- 
![image](https://user-images.githubusercontent.com/3456733/203382734-7b0d36f3-cf3c-4204-b6e5-cd57adf134d1.png)
- Veja os problemas que estão ocorrendo.
- 
![menu-refatoracao](https://user-images.githubusercontent.com/3456733/203382818-44272527-4853-4038-8552-56b0b07914c0.gif)

2022-12-05 17:00 UTC, ronifabio requested changes
Falta resolver os conflitos.
Atualize o seu branch local com as minhas modificações que acabei de subir
Depois, faça o merge local das mudanças do develop para o seu branch.
Então, resolva os conflitos.
Por fim, faça commit e push do seu branch.

2022-12-07 12:22 UTC, ronifabio approved these changes

2022-12-07 12:22 UTC, merged